### ISSUE TITLE
No examples given in README

### ISSUE THREAD

**Issue by jamieparkinson** [harrisonpim/bookworm#1]
Would be nice if there were basic installation instructions + canonical basic example in the README (or at least some kind of index for the ipynbs), currently have to read code to see how stuff works together

**Comment by harrisonpim** [comment]
recent commit adds usage examples in README.md and basic CLI functionality. notebooks are also indexed.

![screenshot](https://user-images.githubusercontent.com/11006680/32462925-1255d128-c333-11e7-892a-2bf0b141bef4.png)
